### ISSUE TITLE
Having issues with script errors.

### ISSUE THREAD

**Issue by crptristen** [TheRealToxicDev/FiveMToDiscord-Docs#1]
```lua
SCRIPT ERROR: @fivemtodiscord/SERVER/Server.lua:243: bad argument #1 to 'gmatch' (string expected, got nil)
> stringsplit (@fivemtodiscord/SERVER/Server.lua:243)
> userCallback (@fivemtodiscord/SERVER/Server.lua:125)
```

this spams everytime somebody types in chat, my devs dont know what it is either so :/

[fivemtodiscord.zip](https://github.com/TheRealToxicDev/FiveMToDiscord-Docs/files/4079370/fivemtodiscord.zip)

**Comment by crptristen** [comment]
File is up there in the zip

**Comment by CodeMeAPixel** [comment]
@crptristen Join our discord for support with this please 👌https://discord.gg/7feb5jN

**Comment by CodeMeAPixel** [comment]
This seems to be a problem with either your webhook set up or the bot attempting to grab steam IDs.... I can better assist you on our Discord......
